before-sleep 'swaylock-plugin --command "swaybg --image=$HOME/Pictures/wallpapers/naruto.png"'
after-resume 'swaylock-plugin --command "swaybg --image=$HOME/Pictures/wallpapers/naruto.png"'
timeout 300 'swaylock-plugin --command "swaybg --image=$HOME/Pictures/wallpapers/naruto.png"'
timeout 300 'brightnessctl -s set 10' resume 'brightnessctl -r'
timeout 330 'mmsg dispatch toggle_monitor,DP-1' resume 'mmsg dispatch toggle_monitor,DP-1'
timeout 900 'systemctl suspend'
